import type { RawPassage } from "./types";

export const BIBLE_KJV_PASSAGES: RawPassage[] = [
  { id: "bible_1",  source_id: "bible_kjv", reference: "Psalms 23:4",    text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me.", context: "Courage in the darkest places", resonance_context: "Về việc đi qua bóng tối mà không sợ hãi nhờ sự đồng hành. Dành cho user đang trong giai đoạn tối tăm nhất của cuộc đời." },
  { id: "bible_2",  source_id: "bible_kjv", reference: "Psalms 46:10",   text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.", context: "Stillness as wisdom", resonance_context: "Về việc dừng lại và biết — không làm gì cũng là một hành động. Dành cho user đang quá bận rộn và cảm thấy mất kết nối với điều gì đó lớn hơn." },
  { id: "bible_3",  source_id: "bible_kjv", reference: "Ecclesiastes 3:1-2", text: "To every thing there is a season, and a time to every purpose under the heaven: a time to be born, and a time to die.", context: "Everything has its right time", resonance_context: "Về việc mọi thứ đều có thời điểm của nó. Dành cho user đang cảm thấy điều gì đó đến quá sớm hoặc quá muộn." },
  { id: "bible_4",  source_id: "bible_kjv", reference: "Ecclesiastes 4:6", text: "Better is an handful with quietness, than both the hands full with travail and vexation of spirit.", context: "Less with peace is better than more with suffering", resonance_context: "Về việc ít hơn nhưng bình yên có giá trị hơn nhiều hơn nhưng căng thẳng. Dành cho user đang hy sinh sự bình yên để có được nhiều hơn." },
  { id: "bible_5",  source_id: "bible_kjv", reference: "Ecclesiastes 11:4", text: "He that observeth the wind shall not sow; and he that regardeth the clouds shall not reap.", context: "Waiting for perfect conditions means never starting", resonance_context: "Về việc chờ đợi điều kiện hoàn hảo là lý do không hành động. Dành cho user đang trì hoãn vì chưa thấy thời điểm 'đúng'." },
  { id: "bible_6",  source_id: "bible_kjv", reference: "Proverbs 4:23",  text: "Keep thy heart with all diligence; for out of it are the issues of life.", context: "The heart is the source of life", resonance_context: "Về tầm quan trọng của việc bảo vệ và chú ý đến nội tâm. Dành cho user đang bỏ qua cảm xúc và trạng thái bên trong của mình." },
  { id: "bible_7",  source_id: "bible_kjv", reference: "Proverbs 11:2",  text: "When pride cometh, then cometh shame: but with the lowly is wisdom.", context: "Humility as the seat of wisdom", resonance_context: "Về mối liên hệ giữa kiêu ngạo và sự sụp đổ. Dành cho user đang cảm thấy tự mãn hoặc đang vật lộn với cái tôi." },
  { id: "bible_8",  source_id: "bible_kjv", reference: "Proverbs 14:12", text: "There is a way which seemeth right unto a man, but the end thereof are the ways of death.", context: "Self-deception is the deepest danger", resonance_context: "Về việc tự lừa dối mình là nguy hiểm nhất. Dành cho user đang theo đuổi điều gì đó và không chắc liệu đó có phải là điều thực sự tốt cho mình không." },
  { id: "bible_9",  source_id: "bible_kjv", reference: "Matthew 6:34",  text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof.", context: "Each day has its own burden", resonance_context: "Về việc lo lắng về tương lai làm giảm khả năng đối phó với hiện tại. Dành cho user đang overwhelm bởi những lo lắng về những gì chưa xảy ra." },
  { id: "bible_10", source_id: "bible_kjv", reference: "Matthew 7:3",   text: "And why beholdest thou the mote that is in thy brother's eye, but considerest not the beam that is in thine own eye?", context: "Self-awareness before judgment of others", resonance_context: "Về việc phán xét người khác thường là phản ánh của điều ta chưa nhìn nhận trong bản thân. Dành cho user đang bực bội với người khác." },
  { id: "bible_11", source_id: "bible_kjv", reference: "John 8:32",     text: "And ye shall know the truth, and the truth shall make you free.", context: "Truth as liberation", resonance_context: "Về việc hiểu sự thật — dù đau — là con đường đến tự do. Dành cho user đang né tránh sự thật vì sợ nó sẽ đau." },
  { id: "bible_12", source_id: "bible_kjv", reference: "Romans 8:28",   text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", context: "Trust in the greater pattern", resonance_context: "Về việc tin vào một quy luật lớn hơn ngay cả khi không thấy rõ. Dành cho user đang trải qua điều xấu và không thể thấy ý nghĩa trong đó." },
  { id: "bible_13", source_id: "bible_kjv", reference: "1 Corinthians 13:12", text: "For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known.", context: "Partial knowledge and humility", resonance_context: "Về việc hiểu biết của con người là không hoàn toàn — và điều đó không sao. Dành cho user đang cảm thấy thất vọng vì không hiểu đủ." },
];
