import type { RawPassage } from "./types";

export const HAFEZ_PASSAGES: RawPassage[] = [
  { id: "hafez_1",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 1",   text: "Hỡi người hầu rượu, bình rượu vòng quanh đi — vì tình yêu lúc đầu dễ dàng nhưng khó khăn đã đến.", context: "Tình yêu dễ bắt đầu khó duy trì", resonance_context: "Về việc mọi tình yêu lớn đều đi kèm thử thách. Dành cho user đang trong giai đoạn khó khăn của mối quan hệ hoặc cam kết." },
  { id: "hafez_2",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 3",   text: "Đừng hỏi ta đi đâu — hãy đi cùng ta. Những nơi ta đến không có tên gọi.", context: "Hành trình vô định nhưng thực", resonance_context: "Về việc một số hành trình không thể lên kế hoạch trước. Dành cho user đang do dự vì không thấy rõ điểm đến." },
  { id: "hafez_3",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 7",   text: "Gió buổi sáng mang theo bí mật của trái tim. Hãy thức dậy và nghe những gì nó nói.", context: "Bình minh mang thông điệp", resonance_context: "Về việc một số hiểu biết chỉ đến trong sự im lặng của buổi sáng sớm. Dành cho user đang bận rộn đến mức không có không gian để nghe nội tâm." },
  { id: "hafez_4",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 14",  text: "Người khôn ngoan nhìn thấy vẻ đẹp của Thượng Đế trong mọi khuôn mặt. Hãy mở mắt ra — vẻ đẹp ở khắp nơi.", context: "Cái thiêng liêng trong cái bình thường", resonance_context: "Về việc tìm thấy điều thiêng liêng trong cái bình thường. Dành cho user đang cảm thấy cuộc sống đang mất đi vẻ đẹp hoặc ý nghĩa." },
  { id: "hafez_5",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 22",  text: "Đừng than vãn về sự bất trung của số phận — ai đã không phải trải qua điều này?", context: "Khó khăn là phần của kinh nghiệm chung", resonance_context: "Về việc đau khổ là trải nghiệm phổ quát của con người. Dành cho user đang cảm thấy đặc biệt bất hạnh so với người khác." },
  { id: "hafez_6",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 33",  text: "Trái tim tôi như gương — nó phản chiếu những gì đứng trước nó. Hãy chú ý đến những gì bạn đặt trước nó.", context: "Trái tim như gương", resonance_context: "Về việc trái tim phản chiếu những gì ta chú ý đến. Dành cho user đang tự hỏi tại sao tâm trạng mình luôn bị ảnh hưởng bởi môi trường xung quanh." },
  { id: "hafez_7",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 41",  text: "Bán đi lòng khôn ngoan của bạn, mua sự ngạc nhiên. Khôn ngoan là đoán. Ngạc nhiên là nhìn thấy.", context: "Ngạc nhiên vượt qua sự chắc chắn", resonance_context: "Về việc sự ngạc nhiên và cởi mở đôi khi dẫn đến hiểu biết sâu hơn sự chắc chắn. Dành cho user đang tự hỏi liệu mình có biết đủ để hành động chưa." },
  { id: "hafez_8",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 55",  text: "Tôi không thể giải thích lửa nào đang thiêu đốt trái tim tôi. Nhưng tôi biết ngọn lửa đó thật.", context: "Trải nghiệm bên trong không cần giải thích", resonance_context: "Về việc một số trải nghiệm nội tâm là thật dù không thể giải thích bằng lý trí. Dành cho user đang cảm thấy điều gì đó mạnh mẽ nhưng không thể gọi tên." },
  { id: "hafez_9",  source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 62",  text: "Người bạo dạn mạo hiểm — người hèn nhát ngồi chờ sự an toàn. Hãy thả mình vào dòng chảy của cuộc sống.", context: "Dũng cảm là tham gia vào cuộc sống", resonance_context: "Về sự khác biệt giữa sống thực sự và sống trong an toàn. Dành cho user đang trốn tránh rủi ro và không biết tại sao mình không hạnh phúc." },
  { id: "hafez_10", source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 79",  text: "Không ai đến gần trái tim người khác nếu không qua nỗi đau. Đau khổ là cái giá của sự thân mật.", context: "Dễ bị tổn thương là cái giá của kết nối", resonance_context: "Về việc kết nối thực sự đòi hỏi sự dễ bị tổn thương. Dành cho user đang giữ khoảng cách với người khác vì sợ bị tổn thương." },
  { id: "hafez_11", source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 88",  text: "Đừng lo về ngày mai. Đêm nay có đủ bóng tối và ánh sáng của nó.", context: "Hiện tại là đủ", resonance_context: "Về việc chú ý vào hiện tại thay vì lo lắng về tương lai. Dành cho user đang bị lo lắng về tương lai bóp nghẹt khả năng tận hưởng hiện tại." },
  { id: "hafez_12", source_id: "hafez_divan", reference: "Hafez · Divan, Ghazal 102", text: "Tôi đã tìm Người ở khắp mọi nơi. Cuối cùng Người ở trong lòng tôi — và tôi đã tìm ở ngoài.", context: "Điều tìm kiếm đã có sẵn bên trong", resonance_context: "Về việc điều chúng ta tìm kiếm bên ngoài thường đã có sẵn bên trong. Dành cho user đang tìm kiếm câu trả lời từ bên ngoài." },
];
