import type { RawPassage } from "./types";

export const MARCUS_AURELIUS_PASSAGES: RawPassage[] = [
  { id: "marcus_1",  source_id: "marcus_aurelius", reference: "Meditations · Book II.1",  text: "Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness.", context: "Preparing for difficulty with equanimity", resonance_context: "Về việc chuẩn bị tâm lý cho khó khăn thay vì bị bất ngờ. Dành cho user đang cảm thấy bị người khác làm thất vọng hoặc phản bội." },
  { id: "marcus_2",  source_id: "marcus_aurelius", reference: "Meditations · Book II.4",  text: "Think not of the remnant of your life as something to be mourned; instead, concentrate on what is here and now.", context: "Presence over regret", resonance_context: "Về việc sống trong hiện tại thay vì tiếc nuối quá khứ hoặc lo lắng tương lai. Dành cho user đang bị mắc kẹt trong 'nếu như' và 'lẽ ra'." },
  { id: "marcus_3",  source_id: "marcus_aurelius", reference: "Meditations · Book II.14", text: "Even if you were to live three thousand more years, or thirty thousand, remember that no one loses any other life than the one he now lives.", context: "The only life is now", resonance_context: "Về sự không thể phủ nhận của thực tế hiện tại. Dành cho user đang chờ đợi một 'cuộc đời khác' thay vì sống cuộc đời đang có." },
  { id: "marcus_4",  source_id: "marcus_aurelius", reference: "Meditations · Book III.6",  text: "Value yourself only by what is really valuable in you — which is nothing more than the choice you are making.", context: "The only true value is your choices", resonance_context: "Về việc giá trị thực của một người nằm trong lựa chọn và hành động, không phải danh tiếng hay của cải. Dành cho user đang định giá bản thân qua những thứ bên ngoài." },
  { id: "marcus_5",  source_id: "marcus_aurelius", reference: "Meditations · Book IV.3",  text: "Men seek retreats for themselves in the country, by the sea, in the hills... but this is altogether unphilosophical. You can retreat into yourself at any moment.", context: "Inner retreat is always available", resonance_context: "Về việc sự bình an không đến từ hoàn cảnh bên ngoài mà từ bên trong. Dành cho user đang cảm thấy cần 'thoát khỏi' cuộc sống hiện tại." },
  { id: "marcus_6",  source_id: "marcus_aurelius", reference: "Meditations · Book IV.7",  text: "Do not indulge in such thoughts as these... 'My life is ruined.' These are the words of a man who does not understand what is happening.", context: "Perspective reframing", resonance_context: "Về việc phân biệt giữa sự kiện thực và diễn giải chúng ta áp đặt lên sự kiện. Dành cho user đang dramatise hoá tình huống." },
  { id: "marcus_7",  source_id: "marcus_aurelius", reference: "Meditations · Book V.8",  text: "On the occasion of every accident that befalls you, remember to turn to yourself and inquire what power you have for turning it to use.", context: "Every obstacle can be turned to use", resonance_context: "Về việc tìm kiếm cơ hội trong mọi trở ngại. Dành cho user đang trong tình huống khó khăn và cảm thấy bất lực." },
  { id: "marcus_8",  source_id: "marcus_aurelius", reference: "Meditations · Book V.16", text: "Such as are your habitual thoughts, such also will be the character of your mind; for the soul is dyed by its thoughts.", context: "Thoughts shape character", resonance_context: "Về việc những suy nghĩ lặp đi lặp lại định hình con người bạn. Dành cho user đang nhận ra mình hay suy nghĩ tiêu cực và muốn thay đổi." },
  { id: "marcus_9",  source_id: "marcus_aurelius", reference: "Meditations · Book VI.2",  text: "How easy it is to repel and to wipe away every impression which is troublesome or unsuitable, and immediately to be in all tranquility.", context: "Choosing your response to impressions", resonance_context: "Về việc chúng ta có quyền lựa chọn phản ứng với mọi sự kiện. Dành cho user đang cảm thấy bị điều khiển bởi cảm xúc phản xạ." },
  { id: "marcus_10", source_id: "marcus_aurelius", reference: "Meditations · Book VI.13", text: "Everything harmonizes with me, which is harmonious to thee, O Universe. Nothing for me is too early or too late, which is in due time for thee.", context: "Acceptance of universal timing", resonance_context: "Về việc chấp nhận thời điểm của vũ trụ thay vì ép buộc. Dành cho user đang cảm thấy mọi thứ đến hoặc đi quá sớm hoặc quá muộn." },
  { id: "marcus_11", source_id: "marcus_aurelius", reference: "Meditations · Book VI.30", text: "Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.", context: "The inner source is always there", resonance_context: "Về nguồn gốc bên trong không bao giờ cạn. Dành cho user cảm thấy mình không còn nguồn lực hoặc động lực." },
  { id: "marcus_12", source_id: "marcus_aurelius", reference: "Meditations · Book VII.9", text: "You have power over your mind — not outside events. Realize this, and you will find strength.", context: "The locus of control", resonance_context: "Về sự phân biệt căn bản giữa những gì trong tầm kiểm soát và những gì không. Dành cho user đang kiệt sức vì cố kiểm soát những thứ không thể kiểm soát." },
  { id: "marcus_13", source_id: "marcus_aurelius", reference: "Meditations · Book VIII.7", text: "Do not look around thee to discover other men's ruling principles, but look straight to this, to what nature leads thee.", context: "Follow your own nature", resonance_context: "Về việc so sánh mình với người khác là nguồn gốc của khổ đau. Dành cho user đang bị ảnh hưởng quá nhiều bởi kỳ vọng của xã hội." },
  { id: "marcus_14", source_id: "marcus_aurelius", reference: "Meditations · Book VIII.47", text: "If you are distressed by anything external, the pain is not due to the thing itself but to your estimate of it; and this you have the power to revoke at any moment.", context: "Pain comes from judgment, not events", resonance_context: "Về nguồn gốc thực sự của đau khổ — không phải sự kiện mà là cách ta diễn giải. Dành cho user đang đau khổ và không biết tại sao." },
  { id: "marcus_15", source_id: "marcus_aurelius", reference: "Meditations · Book IX.3",  text: "Do not waste the rest of your time here worrying about other people, unless it affects the common good. It will keep you from doing something else.", context: "Focus on what matters", resonance_context: "Về việc lo lắng về người khác là cách lãng phí thời gian và năng lực. Dành cho user đang bận tâm quá nhiều về việc người khác nghĩ gì về mình." },
  { id: "marcus_16", source_id: "marcus_aurelius", reference: "Meditations · Book IX.29", text: "When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant... But I have seen the beauty of good, and the ugliness of evil.", context: "Compassion through understanding human nature", resonance_context: "Về việc giữ lòng trắc ẩn dù biết rõ sự yếu đuối của con người. Dành cho user đang cảm thấy thất vọng và cynical về người xung quanh." },
  { id: "marcus_17", source_id: "marcus_aurelius", reference: "Meditations · Book X.8",  text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", context: "Epistemological humility", resonance_context: "Về việc phân biệt ý kiến và sự thật. Dành cho user đang quá chắc chắn về nhận định của mình hoặc đang bị ảnh hưởng bởi ý kiến người khác." },
  { id: "marcus_18", source_id: "marcus_aurelius", reference: "Meditations · Book X.11", text: "Nothing happens to any man that he is not formed by nature to bear.", context: "You are built for what you face", resonance_context: "Về việc khó khăn không vượt quá khả năng chịu đựng của con người. Dành cho user đang cảm thấy không thể tiếp tục." },
  { id: "marcus_19", source_id: "marcus_aurelius", reference: "Meditations · Book XI.13", text: "The obstacle is the way.", context: "Resistance as direction", resonance_context: "Về việc điều cản trở bạn chính là con đường. Dành cho user đang nghĩ cần xóa bỏ trở ngại thay vì học hỏi từ nó." },
  { id: "marcus_20", source_id: "marcus_aurelius", reference: "Meditations · Book XII.23", text: "Everything is in a state of flux, and nothing endures. All things come round and round, and the soul is tortured by this.", context: "Impermanence as a teacher", resonance_context: "Về vô thường như bản chất của thực tại — không phải điều cần sợ mà là điều cần chấp nhận. Dành cho user đang cố giữ chặt điều gì đó đang thay đổi." },
];
