import type { RawPassage } from "./types";

export const RUMI_PASSAGES: RawPassage[] = [
  { id: "rumi_1",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi I.1-4",    text: "Nghe tiếng sáo lau than vãn về sự chia ly. Kể câu chuyện của những cuộc chia cách.", context: "Nỗi đau chia ly là nguồn gốc của tiếng hát", resonance_context: "Về việc nỗi đau chia ly là nguồn gốc của khao khát và sáng tạo. Dành cho user đang đau vì mất mát và không thấy ý nghĩa trong đó." },
  { id: "rumi_2",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi I.10-12",  text: "Ngọn lửa là tình yêu, nước là lý trí. Ngọn lửa tình yêu đốt tất cả lý luận.", context: "Tình yêu vượt qua lý trí", resonance_context: "Về sự đối lập giữa tình yêu và lý trí, và việc tình yêu có thể dẫn đến hiểu biết sâu hơn. Dành cho user đang phân vân giữa quyết định bằng lý trí và quyết định bằng trái tim." },
  { id: "rumi_3",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi I.3810",   text: "Vết thương là nơi ánh sáng đi vào trong bạn.", context: "Đau khổ là cửa mở", resonance_context: "Về việc vết thương không phải là điều cần chữa lành và che đi, mà là nơi sự phát triển thực sự bắt đầu. Dành cho user đang đau và tự hỏi tại sao." },
  { id: "rumi_4",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi II.277",   text: "Bạn không phải là giọt nước trong đại dương. Bạn là toàn bộ đại dương trong một giọt nước.", context: "Mỗi người chứa đựng tất cả", resonance_context: "Về sự đầy đủ và hoàn chỉnh của mỗi cá nhân. Dành cho user cảm thấy mình nhỏ bé và không đủ." },
  { id: "rumi_5",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi III.4232",  text: "Khi bạn đặt chân ra đi và tôi đặt chân ra đi — có một tất yếu trong đó. Mọi sự chia ly đều có sự gặp gỡ ẩn bên trong.", context: "Mỗi chia ly chứa đựng cuộc gặp gỡ", resonance_context: "Về việc chia tay và kết thúc không phải là mất mát hoàn toàn. Dành cho user đang trải qua sự kết thúc của một mối quan hệ hoặc giai đoạn." },
  { id: "rumi_6",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi I.1730",   text: "Im lặng là biển của tri thức. Lời nói như bờ biển — đến từ biển và trở về biển.", context: "Tri thức sâu hơn lời nói", resonance_context: "Về việc những điều quan trọng nhất không thể nói ra đầy đủ. Dành cho user đang cảm thấy không thể diễn đạt điều họ đang trải qua." },
  { id: "rumi_7",  source_id: "rumi_masnavi", reference: "Rumi · Divan-i Kebir",    text: "Vì tình yêu bạn học được điều bạn chưa bao giờ biết. Vì tình yêu bạn trở thành điều bạn chưa bao giờ là.", context: "Tình yêu như sự chuyển hoá", resonance_context: "Về việc tình yêu — không chỉ tình lãng mạn mà cả tình yêu với cuộc sống — là động lực của sự phát triển. Dành cho user cảm thấy mắc kẹt và không thay đổi được." },
  { id: "rumi_8",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi I.130",    text: "Đừng buồn. Bất cứ điều gì bạn mất đi đều đến với bạn ở dạng khác.", context: "Mất mát và chuyển hoá", resonance_context: "Về việc những gì ta mất đôi khi trở lại trong hình dạng khác, phù hợp hơn. Dành cho user đang đau vì mất mát và chưa thấy điều gì có thể thay thế." },
  { id: "rumi_9",  source_id: "rumi_masnavi", reference: "Rumi · Masnavi IV.3319",  text: "Hãy sống ở nơi bạn sợ sống. Sự phá huỷ nơi đó là bắt đầu của điều bạn cần.", context: "Đối mặt với sợ hãi", resonance_context: "Về việc nơi chúng ta sợ nhất thường là nơi chứa đựng sự tăng trưởng thực sự. Dành cho user đang tránh né một điều gì đó vì sợ hãi." },
  { id: "rumi_10", source_id: "rumi_masnavi", reference: "Rumi · Masnavi VI.4703",  text: "Ngoài ý tưởng về điều đúng và điều sai, có một cánh đồng. Tôi sẽ gặp bạn ở đó.", context: "Không gian vượt qua phán xét", resonance_context: "Về không gian vượt qua các phán xét đúng sai, một nơi mà kết nối thực sự có thể xảy ra. Dành cho user đang bị kẹt trong tranh luận về đúng sai." },
  { id: "rumi_11", source_id: "rumi_masnavi", reference: "Rumi · Masnavi II.1751",  text: "Chúng ta là một, tôi là bạn và bạn là tôi. Cái thân xác chia cắt chúng ta — nhưng chúng ta là một linh hồn.", context: "Sự hợp nhất bên dưới sự phân cách", resonance_context: "Về việc sự chia cắt chỉ là bề mặt. Dành cho user đang cảm thấy cô đơn và tách biệt với người khác." },
  { id: "rumi_12", source_id: "rumi_masnavi", reference: "Rumi · Masnavi I.3056",   text: "Người tìm kiếm là người tìm thấy. Hành trình tìm kiếm là chính sự tìm thấy.", context: "Hành trình chính là điểm đến", resonance_context: "Về việc sự tìm kiếm tự nó đã là một dạng tìm thấy. Dành cho user đang cảm thấy tìm kiếm mãi mà không thấy." },
];
